import QRCode from 'qrcode';
// Vue 2 page components used by the recovered uni-app router in shared mode.
(function () {
  const titles={hub:'业务中心',withdraw:'提现',account:'收款账户',identity:'身份资料',password:'账号安全',warehouse:'我的仓库',market:'寄卖市场',team:'我的团队',messages:'站内消息',share:'邀请好友',circle:'分享素材',recharge:'充值申请',register:'账号登录'};
  const paths={hub:'/pages/personal/poster',withdraw:'/pages/personal/record',account:'/pages/order/shoukm',identity:'/pages/personal/identify',password:'/pages/personal/passwordone',warehouse:'/pages/order/order',team:'/pages/personal/team',circle:'/pages/index/faquan',recharge:'/pages/personal/recharge'};
  const style=document.createElement('style');style.textContent='.tea-workflow{font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#243a30;background:#f7f9f6;min-height:100vh;padding:20px 18px 90px;box-sizing:border-box;max-width:760px;margin:auto}.tea-workflow h1{font-size:24px;margin:12px 0}.tea-workflow h2{font-size:18px;margin:16px 0 8px}.tea-workflow p{margin:8px 0;overflow-wrap:anywhere}.tea-workflow nav{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0 20px}.tea-workflow button{font:inherit;background:#287352;color:#fafcf9;border:1px solid #287352;border-radius:6px;padding:9px 13px;min-height:44px;margin:5px 8px 5px 0;cursor:pointer}.tea-workflow nav button,.tea-workflow button.secondary{color:#285c43;background:#f1f6ef}.tea-workflow button:disabled{opacity:.55;cursor:wait}.tea-workflow label{display:block;margin:14px 0 4px}.tea-workflow input,.tea-workflow select,.tea-workflow textarea{display:block;box-sizing:border-box;width:100%;min-height:44px;border:1px solid #aebcaf;border-radius:5px;background:#fcfdfb;color:#203b2e;padding:10px;font:inherit}.tea-workflow section{padding:14px 0;border-bottom:1px solid #d8e0d7}.tea-workflow img{max-width:100%;height:auto}.tea-workflow .status{background:#e7f0e4;padding:12px;border-radius:6px;white-space:pre-wrap}.tea-workflow .error{background:#fbebe6;color:#8e3228}.tea-workflow small{color:#526356}.tea-workflow a{color:#236b49;overflow-wrap:anywhere}.tea-workflow :focus-visible{outline:3px solid #73a08a;outline-offset:2px}';document.head.appendChild(style);
  window.__teaWorkflowPage=function(kind) {
    return {data(){return {kind,view:kind,loading:true,busy:false,error:'',success:'',data:{},rows:[],profile:{},form:{},addresses:[],selected:null,productId:0,requestId:crypto.randomUUID()};},onLoad(options={}){if(options.mode==='share'){this.view='share';this.productId=options.goods_id || 0;}if(kind==='register'){uni.reLaunch({url:'/pages/login/login'});return;}this.load();},onShow(){if(kind!=='register')this.load();},
      methods:{
        async api(route,p,method='POST') {const response=await fetch((window.__H5_API_BASE__ || '/app')+route,{method,headers:{token:uni.getStorageSync('TOKEN') || '','Content-Type':'application/json'},...(method==='GET'?{}:{body:JSON.stringify(p || {})})});const body=await response.json();if(body.code!==1)throw new Error(body.msg || '操作失败，请重试');return body.data;},
        async run(action, message='操作已保存') {if(this.busy)return;this.busy=true;this.error='';this.success='';try{await action();this.success=message;this.form.pay_password='';this.requestId=crypto.randomUUID();await this.load();}catch(error){this.error=error.message;}finally{this.busy=false;}},
        async load(){this.loading=true;this.error='';try{
          if(!uni.getStorageSync('TOKEN')){this.error='请先登录，账号由管理员建立。';return;}
          if(this.view==='withdraw'){this.data=await this.api('/member/withdrawalInfo');this.rows=this.data.records;}
          else if(this.view==='account'){this.profile=await this.api('/member/getMemberDetails');if(!this.form.bank_card)this.form={...this.profile.pay_info};}
          else if(this.view==='identity')this.data=await this.api('/certification/status');
          else if(this.view==='warehouse'){this.rows=await this.api('/warehouse/list');const addresses=await this.api('/address/list');this.addresses=Array.isArray(addresses)?addresses:addresses.list || [];}
          else if(this.view==='market')this.rows=await this.api('/market/list');
          else if(this.view==='messages')this.rows=await this.api('/member/notifications');
          else if(this.view==='team'){this.data=await this.api('/member/getMyIndirection',{limit:100});this.rows=this.data.list;this.profile=await this.api('/team/getTeamInfo');}
          else if(this.view==='share'){this.data=await this.api('/member/share');if(this.productId){const product=await this.api('/shopgoods/getDetails',{goods_id:this.productId});this.data={...this.data,product:product.detail,path:'/#/pages/classify/goodsdet?id='+this.productId+'&invite='+encodeURIComponent(this.data.invitation_code)};}}
          else if(this.view==='circle')this.rows=await this.api('/circle/getList');
          else if(this.view==='recharge'){this.data=await this.api('/index/getStoreInfo');const records=await this.api('/recharge/lists');this.rows=records.list?.data || records.list || [];}
          else if(this.view==='hub'){this.profile=await this.api('/member/getMemberDetails');this.rows=await this.api('/order/subscriptions');}
        }catch(e){this.error=e.message;}finally{this.loading=false;}},
        switchView(view){this.view=view;this.form={};this.selected=null;this.success='';this.load();},
        field(h,key,label,type='text'){return h('label',[label,h('input',{attrs:{type,'aria-label':label,autocomplete:type==='password'?'new-password':'off'},domProps:{value:this.form[key] || ''},on:{input:e=>this.$set(this.form,key,e.target.value)}})]);},
        button(h,label,action,secondary=false){return h('button',{class:{secondary},attrs:{type:'button',disabled:this.busy},on:{click:action}},label);},
        async upload(event){const file=event.target.files[0];if(!file)return;if(file.size>1024*1024){this.error='图片不能超过1MB';return;}this.busy=true;try{const data=new FormData();data.append('file',file);const response=await fetch((window.__H5_API_BASE__ || '/app')+'/upload/image',{method:'POST',headers:{token:uni.getStorageSync('TOKEN') || ''},body:data});const body=await response.json();if(body.code!==1)throw new Error(body.msg);this.$set(this.form,'pay_image',body.data.file_path);this.success='凭证已上传';}catch(e){this.error=e.message;}finally{this.busy=false;}},
        async choose(item,action){this.selected=item;this.form={action};this.error='';this.success='';if(action==='listing'){try{const quote=await this.api('/order/getServiceCharge',{order_id:item.order_id});this.$set(this.form,'quoted_fee',quote.e_price);}catch(e){this.error=e.message;this.selected=null;}}},
        async savePoster(){await this.run(async()=>{const url=location.origin+(this.data.path || '/');const qr=document.createElement('canvas');await QRCode.toCanvas(qr,url,{width:320,margin:2});const canvas=document.createElement('canvas');canvas.width=600;canvas.height=760;const context=canvas.getContext('2d');context.fillStyle='#f7f9f6';context.fillRect(0,0,600,760);context.fillStyle='#285c43';context.textAlign='center';context.font='bold 38px sans-serif';context.fillText('鑫芮茶业',300,95);context.font='24px sans-serif';context.fillText(this.data.product?this.data.product.goods_name.slice(0,20):'一盏好茶，与好友分享',300,145);context.drawImage(qr,140,205);context.fillText('邀请码：'+this.data.invitation_code,300,600);context.font='18px sans-serif';context.fillText('扫码浏览商城，联系管理员建立账号',300,652);const link=document.createElement('a');link.href=canvas.toDataURL('image/png');link.download='鑫芮茶业-邀请海报.png';link.click();},'邀请海报已生成');},
        submitWarehouse(){const s=this.selected,p={...this.form,order_id:s.order_id};const route={listing:'/warehouse/listing',delivery:'/warehouse/delivery',split:'/order/toSplitOrder',buy:'/market/buy',pay:'/warehouse/pay'}[p.action];if(p.action==='buy')p.request_id=this.requestId;this.run(async()=>{await this.api(route,p);this.selected=null;});},
      },render(h){const children=[],field=(k,l,t)=>this.field(h,k,l,t),button=(l,a,s)=>this.button(h,l,a,s),submit=(r,p,m)=>this.run(()=>this.api(r,p),m);
        children.push(h('nav',[button('个人中心',()=>uni.switchTab({url:'/pages/personal/personal'}),true),button('业务中心',()=>this.switchView('hub'),true)]),h('h1',titles[this.view] || titles.hub));
        if(this.error)children.push(h('p',{class:'status error',attrs:{role:'alert'}},this.error));if(this.success)children.push(h('p',{class:'status',attrs:{role:'status'}},this.success));
        if(!uni.getStorageSync('TOKEN')){children.push(button('账号登录',()=>uni.navigateTo({url:'/pages/login/login'})),h('p','忘记密码请联系管理员重置。'));return h('div',{class:'tea-workflow'},children);}
        if(this.loading){children.push(h('p',{attrs:{role:'status'}},'正在读取…'));return h('div',{class:'tea-workflow'},children);}
        if(this.view==='hub')children.push(h('p',(this.profile.nickName || '会员')+' · 余额 ¥'+(this.profile.amount || '0.00')),h('nav',Object.keys(titles).filter(k=>!['hub','register'].includes(k)).map(k=>button(titles[k],()=>this.switchView(k),true))),h('h2','已预约场次'),...(this.rows.length?this.rows.map(x=>h('section',[h('p',x.title),h('small',x.startTime+' · '+x.status)])):[h('p','暂无预约，可在抢购页面预约场次。')]));
        if(this.view==='withdraw')children.push(h('p','可提现 ¥'+(this.data.available || '0.00')),h('p','最低 '+this.data.minimum+' 元，手续费 '+this.data.feeRate+'%。提交后冻结申请金额，审核后由财务人工打款。'),button('设置收款账户',()=>this.switchView('account'),true),field('amount','提现金额','number'),field('pay_password','交易密码','password'),button('提交提现',()=>submit('/member/withdraw',{...this.form,feeRate:this.data.feeRate,request_id:this.requestId},'提现申请已提交')),h('h2','提现记录'),...this.rows.map(x=>h('section',[h('p','¥'+x.amount+' · '+x.status_text),h('p','实际到账 ¥'+x.actual_amount+'，手续费 ¥'+x.fee),h('small',x.create_time),x.remark?h('p',x.remark):null])));
        if(this.view==='account')children.push(h('p','仅保存提现收款资料，不会开通第三方快捷支付。'),field('bank','开户银行'),field('bank_name','收款人姓名'),field('bank_card','银行卡号'),field('bank_branch','开户支行'),field('pay_password','交易密码','password'),button('保存收款账户',()=>submit('/member/setPay',this.form,'收款账户已保存')));
        if(this.view==='identity')children.push(h('p','状态：'+(this.data.status || '未提交')),h('p','由管理员线下核对身份证件后审核。这里只填写姓名和证件末四位。'),this.data.remark?h('p',this.data.remark):null,field('certification_name','真实姓名'),field('id_last_four','证件末四位'),button('提交身份资料',()=>submit('/certification/addRealName',this.form,'资料已提交人工核验')));
        if(this.view==='password')children.push(h('h2','修改登录密码'),field('old_password','原登录密码','password'),field('password','新登录密码（至少八位）','password'),field('real_pwd','再次输入新登录密码','password'),button('修改登录密码',()=>this.run(async()=>{await this.api('/member/editPwd',this.form);uni.removeStorageSync('TOKEN');uni.reLaunch({url:'/pages/login/login'});})),h('h2','设置交易密码'),field('loginPassword','当前登录密码','password'),field('pay_password','新的六位交易密码','password'),button('保存交易密码',()=>submit('/member/changePayPassword',{password:this.form.loginPassword,pay_password:this.form.pay_password})));
        if(['warehouse','market'].includes(this.view)){
          children.push(h('nav',[button('我的仓库',()=>this.switchView('warehouse'),true),button('寄卖市场',()=>this.switchView('market'),true)]));
          if(this.selected){const action=this.form.action;children.push(h('section',[h('h2',this.selected.goods_name),action==='listing'?h('p','本次服务费 ¥'+(this.form.quoted_fee ?? '读取中')+'，从余额扣除，撤回寄卖不退还服务费。'):null,action==='buy'?h('p','本批共 '+this.selected.quantity+' 件，支付 ¥'+this.selected.price+'，从余额扣除。'):null,action==='listing'?field('sale_price','整批寄卖总价','number'):null,action==='split'?field('quantity','拆分件数','number'):null,action==='delivery'?h('label',['收货地址',h('select',{attrs:{'aria-label':'收货地址'},domProps:{value:this.form.address_id || ''},on:{change:e=>this.$set(this.form,'address_id',e.target.value)}},[h('option',{attrs:{value:''}},'请选择'),...this.addresses.map(a=>h('option',{attrs:{value:a.address_id}},a.name+' '+a.phone+' '+a.detail))])]):null,['listing','buy','pay'].includes(action)?field('pay_password','交易密码','password'):null,button('确认提交',()=>this.submitWarehouse()),button('取消',()=>{this.selected=null;},true)]));}
          children.push(...this.rows.map(x=>h('section',[h('h2',x.goods_name),h('p',this.view==='market'?'¥'+x.price+' · '+x.quantity+'件 · '+x.seller:'订单 '+x.order_no+' · '+(x.goods_num || 1)+'件 · '+x.pay_status),this.view==='market'&&!x.owner?button('购买',()=>this.choose(x,'buy')):null,this.view==='warehouse'&&x.pay_status==='结算完毕'?h('div',[button('寄卖',()=>this.choose(x,'listing')),button('提货',()=>this.choose(x,'delivery')),Number(x.goods_num)>1?button('拆分',()=>this.choose(x,'split')):null]):null,this.view==='warehouse'&&x.pay_status==='寄卖中'?button('撤回寄卖',()=>submit('/warehouse/cancelListing',{order_id:x.order_id},'寄卖已撤回，已收取服务费不退')):null,this.view==='warehouse'&&x.pay_status==='待支付'?button('余额支付',()=>this.choose(x,'pay')):null,x.delivery_order_id?button('查看提货订单',()=>uni.navigateTo({url:'/pages/order/shoporder?showTab=all'}),true):null])));
        }
        if(this.view==='messages')children.push(...this.rows.map(x=>h('section',[h('h2',x.title),h('p',x.content),h('small',x.create_time),!x.read?button('标为已读',()=>submit('/member/readNotification',{id:x.id})):h('small',' · 已读')])));
        if(this.view==='team')children.push(h('p','当前等级：'+(this.profile.level || '普通会员')+'，本人已收货消费 ¥'+(this.profile.ownSpend || '0.00')),h('p','直属 '+(this.data.direct_count || 0)+' 人，间接 '+(this.data.indirect_count || 0)+' 人'),h('p','团队已收货业绩 ¥'+(this.data.total_performance || '0.00')+'，累计分佣 ¥'+(this.profile.money || '0.00')),h('p','仅展示实际绑定成员及已确认收货的订单。'),...this.rows.map(x=>h('section',[h('h2',x.nickName),h('p',x.mobile),h('p','已收货消费 ¥'+x.consumption_amount)])));
        if(this.view==='share'){const url=location.origin+(this.data.path || '/');children.push(this.data.product?h('h2',this.data.product.goods_name):null,h('p','邀请码：'+(this.data.invitation_code || '')),h('p','好友联系管理员建立账号时，提供此邀请码即可绑定关系。'),h('a',{attrs:{href:url}},url),button('下载邀请海报',()=>this.savePoster()),button('复制邀请链接',()=>this.run(()=>navigator.clipboard.writeText(url),'邀请链接已复制')),h('section',[h('h2','鑫芮茶业'),h('p','一盏好茶，与好友分享'),h('p','邀请人：'+(this.data.invitation_code || ''))]));}
        if(this.view==='circle')children.push(...this.rows.map(x=>h('section',[h('h2',x.title),h('p',x.content),...(x.images || []).map(src=>h('a',{attrs:{href:src,target:'_blank',rel:'noopener'}},[h('img',{attrs:{src,alt:x.title || '分享图片',loading:'lazy'}})])),button('复制文案',()=>this.run(async()=>{await navigator.clipboard.writeText(x.content || x.title || '');await this.api('/circle/download',{id:x.id});},'文案已复制'))])));
        if(this.view==='recharge')children.push(h('p','转账后上传凭证，财务核对到账后入账。不要在未转账时提交凭证。'),h('p',this.data.pay?.bank?'收款银行：'+this.data.pay.bank+'，户名：'+this.data.pay.bank_name+'，账号：'+this.data.pay.bank_card:'收款信息尚未配置，请联系商家。'),field('custom_price','充值金额','number'),h('label',['入账账户',h('select',{attrs:{'aria-label':'入账账户'},on:{change:e=>this.$set(this.form,'asset',e.target.value)}},[h('option',{attrs:{value:'amount'}},'余额'),h('option',{attrs:{value:'score'}},'积分')])]),h('label',['转账凭证',h('input',{attrs:{type:'file',accept:'image/png,image/jpeg','aria-label':'转账凭证'},on:{change:this.upload}})]),button('提交充值申请',()=>submit('/recharge/toOrder',{...this.form,asset:this.form.asset || 'amount'},'充值申请已提交，等待核实到账')));
        if(['market','warehouse','messages','team','circle'].includes(this.view)&&!this.rows.length&&!this.error)children.push(h('p','暂无记录。'));
        return h('div',{class:'tea-workflow'},children);
      }};
  };
})();
